[package]
name = "mdbook-twiki"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "twiki backend for mdbook"

[dependencies]
mdbook = "0.4.20"
pulldown-cmark = "0.9.1"
serde = "1.0.139"
serde_derive = "1.0.139"
